# Name:   Tahir Waseem
# Roll No: PIAIC81613
# Quarter: 2nd
# Instructor: Sir Qasim

# Numpy Assignment

# Import Numpy

In [2]:
import numpy as np

# 1-np.array()

In [2]:
arr=np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


## Dimensions in Array
### 0-D array

In [8]:
arr0d=np.array(50)
print(arr0d)

50


### 1-D array

In [9]:
arr1d=np.array([1,2,3,4,5])
print(arr1d)

[1 2 3 4 5]


### 2-D array

In [10]:
arr2d=np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


### 3-D array

In [11]:
arr3d=np.array([[[1, 2, 3],
                 [4, 5, 6]],
                [[1, 2, 3],
                 [4, 5, 6]]])
print(arr3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## 2-ndim For array Dimension

In [14]:
a=np.ndim(arr0d)
b=np.ndim(arr1d)
c=np.ndim(arr2d)
d=np.ndim(arr3d)
print(a)
print(b)
print(c)
print(d)

0
1
2
3


### Create Array with ndim

In [15]:
arr=np.array([1, 2, 3, 4],ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## 3-Arange()

In [16]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


## 4-Reshape() 2D and 3D

In [19]:
arr2d=np.arange(15).reshape(5,3)
print(arr2d)
arr3d=np.arange(8).reshape(2,2,2)
print(arr3d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


## 5-Shape Attribute

In [20]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]).shape
print(arr)

(2, 4)


## 6-View Base attribute

In [23]:
arr=np.arange(1,11).reshape(2,5).base
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


## 7-random() 8-rand()

In [29]:
arr=np.random.rand()
print(arr)

0.1424696334536103


## 8-randint() 

In [31]:
arr=np.random.randint(15)
print(arr)

12


## 9-randint() with size aurgument

In [32]:
arr=np.random.randint(10,size=(5))
print(arr)

[0 0 7 9 6]


## 10-choice()

In [34]:
arr=np.random.choice([3, 5, 7, 9])
print(arr)

7


## 11-uniform()

In [43]:
arr=np.random.uniform(size=(2,2))
print(arr)

[[0.49576242 0.0955823 ]
 [0.68942227 0.10080906]]


## 12-concatenate()

In [57]:
arr1=np.arange(1,11).reshape(2,5)
arr2=np.arange(11,21).reshape(2,5)
print(arr1)
print(arr2)
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## 13-stack()

In [58]:
arr1=np.array([[1, 2, 3],[7,8,9]])
arr2=np.array([[4, 5, 6],[10,11,12]])
arr=np.stack((arr1, arr2), axis=1)
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 14-add()

In [35]:
x = np.arange(1,6)
y = np.arange(4,9)
print(x)
print(y)
z = np.add(x, y)
print(z)

[1 2 3 4 5]
[4 5 6 7 8]
[ 5  7  9 11 13]


## 15-subtract()

In [61]:
z=np.subtract(y,x)
print(z)

[3 3 3 3]


## 16-multiply()

In [62]:
z=np.multiply(x,y)
print(z)

[ 4 10 18 28]


## 17-divide()

In [63]:
z=np.divide(x,y)
print(z)

[0.25       0.4        0.5        0.57142857]


## 18-power()

In [64]:
z=np.power(x,y)
print(z)

[    1    32   729 16384]


## 19-mod()

In [66]:
z=np.mod(y,x)
print(z)

[0 1 0 3]


## 20-divmod()

In [67]:
z=np.divmod(y,x)
print(z)

(array([4, 2, 2, 1], dtype=int32), array([0, 1, 0, 3], dtype=int32))


## 21-absolute()

In [68]:
arr=np.array([-1, -2, 1, 2, 3, -4])
newarr=np.absolute(arr)
print(newarr)

[1 2 1 2 3 4]


## 22-slicing

In [52]:
arr=np.arange(15,31)
print(arr)
print(arr[3:8])

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
[18 19 20 21 22]


## 23-unique() 

In [60]:
arr = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
farr=np.unique(arr,axis=0)
print(farr)

['Bob' 'Joe' 'Will']


## 24-delete()

In [5]:
arr = np.array([[34,43,73],
                [82,22,12],
                [53,94,66]])
newarr=np.delete(arr,1,1)
print(newarr)

[[34 73]
 [82 12]
 [53 66]]


## 25-insert()

In [6]:
finalarr=np.insert(newarr,1,10,axis=1)
print(finalarr)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


## 26-where()

In [7]:
arr2d=np.array([[1, 2, 3],
            [4, 5, 6], 
            [7, 8, 9]])
newarr=np.where(arr2d==5,12,arr2d)
print(newarr)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


## 27-setdiff1d()

In [8]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
result=np.setdiff1d(a, b)
print(result)

[1 2 3 4]


## 28-max()

In [9]:
arr=np.random.randint(12,size=(5))
print(arr)
farr=arr.max(axis=0)
print(farr)

[ 1  2  7 11  5]
11


## 29-min()

In [10]:
print(arr)
farr=arr.min(axis=0)
print(farr)

[ 1  2  7 11  5]
1


## 30-resize()

In [11]:
arr=np.array([1, 2, 3, 4, 5, 6])
farr=arr.resize(2,3)
print(arr)

[[1 2 3]
 [4 5 6]]


## 31-transpose()

In [16]:
arr=np.arange(9).reshape(3,3)
print(arr)
farr=arr.transpose()
print(farr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


## 32-flipud()

In [18]:
arr=np.arange(10)
print(arr)
farr=np.flipud(arr)
print(farr)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


## 33-trunc()

In [19]:
arr=np.trunc([-3.1666, 3.6667])
print(arr)

[-3.  3.]


## 34-asfarray()

In [33]:
arr=np.arange(2,17).reshape(5,3)
farr=np.asfarray(arr)
print(farr)

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]
 [11. 12. 13.]
 [14. 15. 16.]]


## 35-swapaxes()

In [28]:
arr=np.arange(8).reshape(2,2,2)
print(arr)
farr=np.swapaxes(arr,0,1)
print(farr)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]


## 36-around()

In [37]:
arr=np.array([2.5236,65.589,26.7889])
farr=np.around(arr,2)
print(farr)

[ 2.52 65.59 26.79]


## 37-floor()

In [38]:
farr=np.floor(arr)
print(farr)

[ 2. 65. 26.]


## 38-ceil()

In [39]:
farr=np.ceil(arr)
print(farr)

[ 3. 66. 27.]


## 39-log2()

In [41]:
arr=np.arange(30,41)
farr=np.log2(arr)
print(farr)

[4.9068906  4.95419631 5.         5.04439412 5.08746284 5.12928302
 5.169925   5.20945337 5.24792751 5.28540222 5.32192809]


## 40-log10()

In [42]:
farr=np.log10(arr)
print(farr)

[1.47712125 1.49136169 1.50514998 1.51851394 1.53147892 1.54406804
 1.5563025  1.56820172 1.5797836  1.59106461 1.60205999]


## 41-log() 

In [43]:
farr=np.log(arr)
print(farr)

[3.40119738 3.4339872  3.4657359  3.49650756 3.52636052 3.55534806
 3.58351894 3.61091791 3.63758616 3.66356165 3.68887945]


## 42-searchsorted() 

In [44]:
arr=np.arange(1,10)
print(np.searchsorted(arr,8))

7


## 43-sort()

In [46]:
arr=np.random.randint(10,size=(6))
print(arr)
print(np.sort(arr))

[3 4 9 5 0 6]
[0 3 4 5 6 9]


## 44-array_split()

In [53]:
print(np.array_split(arr,5))

[array([15, 16, 17, 18]), array([19, 20, 21]), array([22, 23, 24]), array([25, 26, 27]), array([28, 29, 30])]


## 45-flip()

In [59]:
arr=np.arange(100).reshape(10,10)
print(arr)
print("FLIPPING")
farr=np.flip(arr)
print(farr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
FLIPPING
[[99 98 97 96 95 94 93 92 91 90]
 [89 88 87 86 85 84 83 82 81 80]
 [79 78 77 76 75 74 73 72 71 70]
 [69 68 67 66 65 64 63 62 61 60]
 [59 58 57 56 55 54 53 52 51 50]
 [49 48 47 46 45 44 43 42 41 40]
 [39 38 37 36 35 34 33 32 31 30]
 [29 28 27 26 25 24 23 22 21 20]
 [19 18 17 16 15 14 13 12 11 10]
 [ 9  8  7  6  5  4  3  2  1  0]]


## 46-nditer()

In [3]:
arr=np.arange(8).reshape(2,2,2)
for x in np.nditer(arr):
  print(x)

0
1
2
3
4
5
6
7


## 47-ndenumerate()

In [6]:
for x in np.ndenumerate(arr):
    print(x)

((0, 0, 0), 0)
((0, 0, 1), 1)
((0, 1, 0), 2)
((0, 1, 1), 3)
((1, 0, 0), 4)
((1, 0, 1), 5)
((1, 1, 0), 6)
((1, 1, 1), 7)


## 48-copy()

In [10]:
arr=np.arange(10)
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  1  2  3  4  5  6  7  8  9]
[0 1 2 3 4 5 6 7 8 9]


## 49-view()

In [11]:
arr=np.arange(10)
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  1  2  3  4  5  6  7  8  9]
[42  1  2  3  4  5  6  7  8  9]


## 50-reduce()

In [17]:
arr=np.arange(3,10,3)
x=np.lcm.reduce(arr)
print(arr)
print(x)

[3 6 9]
18


# The End